<ArcPad>
	<LAYER>
		<SYMBOLOGY>
			<SIMPLELABELRENDERER field="NAME" rotationfield="" visible="false" expression="" language="">
				<TEXTSYMBOL fontcolor="Black" font="Tahoma" fontstyle="regular" fontsize="9"/>
			</SIMPLELABELRENDERER>
			<SIMPLERENDERER>
				<SIMPLELINESYMBOL color="Aquamarine" width="1"/>
			</SIMPLERENDERER>
		</SYMBOLOGY>
		<QUERY where=""/>
		<METADATA/>
	</LAYER>
</ArcPad>
